window.addEventListener('error',e=>console.error('JS ERROR',e.message));
let catalog=Admin.load().filter(isValidProduct); let activeCoupon=null;
const $=s=>document.querySelector(s); const fmt=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);

function finalPrice(p){let v=Discounts.apply(p); if(activeCoupon?.type==='all')v=Math.round(v*.9); if(activeCoupon?.type==='river'&&p.team==='river')v=Math.round(v*.85); if(activeCoupon?.type==='first')v=Math.round(v*.8); return v;}
function searchMatch(p,q){q=q.toLowerCase();const t=`${p.name} ${p.description}`.toLowerCase(); if(t.includes(q))return true; return q.split('').every(c=>t.includes(c));}
function getFiltered(){const q=$('#search').value.trim();const cat=$('#filterCat').value;const onlyDeals=$('#onlyDeals').checked; return catalog.filter(p=>{if(cat!=='todas'&&p.category!==cat)return false; if(q&&!searchMatch(p,q))return false; const deal=finalPrice(p)<p.price; if(onlyDeals&&!deal)return false; return true;});}

function renderCatalog(){const list=getFiltered(); const root=$('#catalog'); if(!list.length){root.innerHTML='<div class="panel">Sin resultados</div>';return;} root.innerHTML=list.map(p=>{const fp=finalPrice(p); const off=Math.round((1-fp/p.price)*100); Analytics.hit(p.id,'v'); return `<article class='card reveal'><img loading='lazy' src='${p.img}' alt='${p.name}'><div class='cbody'><small>${p.category}</small><h3>${p.name}</h3><p>${p.description}</p><p class='price'>${fmt(fp)} <span class='ref'>${fmt(p.referencePrice)}</span></p><span class='off'>-${off}% OFF</span><div class='row'><button data-add='${p.id}'>Agregar</button><button data-f='${p.id}'>${Wishlist.has(p.id)?'Quitar ❤':'❤'}</button></div></div></article>`;}).join('');
  document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=catalog.find(x=>x.id===b.dataset.add);Cart.add(p);Analytics.hit(p.id,'a');renderCart();toast('Agregado');});
  document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{Wishlist.toggle(b.dataset.f);renderCatalog();});
  reveal();
}

function renderCart(){const c=Cart.items; $('#cartQty').textContent=c.reduce((a,i)=>a+i.qty,0); $('#cartList').innerHTML=c.map(i=>`<div class='panel'><b>${i.name}</b><p>${fmt(finalPrice(i))}</p><input data-q='${i.id}' type='number' value='${i.qty}' min='1'><button data-r='${i.id}'>Eliminar</button></div>`).join('')||'<p>Carrito vacío</p>'; document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{Cart.remove(b.dataset.r);renderCart();}); document.querySelectorAll('[data-q]').forEach(i=>i.onchange=()=>{Cart.setQty(i.dataset.q,Number(i.value));renderCart();}); const total=c.reduce((a,i)=>a+finalPrice(i)*i.qty,0); $('#cartTotal').textContent=`Total: ${fmt(total)}`; $('#waLink').href=`https://wa.me/5493425550198?text=${encodeURIComponent('Hola, quiero comprar:\n'+c.map(i=>`- ${i.name} x${i.qty}`).join('\n')+'\nTotal: '+fmt(total))}`;}

function initAuth(){const s=Auth.session();const btn=document.createElement('button');btn.textContent=s?`Salir ${s.name}`:'Ingresar';btn.onclick=()=>{if(Auth.session()){Auth.logout();location.reload();return;}const mode=prompt('login/register');const email=prompt('email');const pass=prompt('pass');if(mode==='register'){const name=prompt('nombre');Auth.register(name,email,pass)?toast('Registrado'):toast('Error registro');}else{Auth.login(email,pass)?toast('Login ok'):toast('Credenciales inválidas');}setTimeout(()=>location.reload(),300);};document.querySelector('.top').appendChild(btn);}
function initAdmin(){const s=Auth.session();if(!s||s.role!=='admin')return; $('#adminRoot').innerHTML=`<h3>Admin</h3><form id='af'><input id='n' placeholder='Nombre' required><input id='pr' type='number' placeholder='Precio' required><select id='ct'><option>camisetas</option><option>botines</option><option>pelotas</option><option>shorts</option></select><input id='im' placeholder='Imagen URL' required><input id='ds' placeholder='Descripción' required><button>Guardar</button></form>`; $('#af').onsubmit=e=>{e.preventDefault();const p={id:'a'+Date.now(),name:n.value,category:ct.value,price:Number(pr.value),referencePrice:Math.round(Number(pr.value)*1.12),img:im.value,description:ds.value}; if(!Admin.valid(p))return toast('Datos inválidos'); catalog.push(p); Admin.save(catalog); renderCatalog(); toast('Producto creado');};}

function bind(){ $('#search').oninput=renderCatalog; $('#filterCat').onchange=renderCatalog; $('#onlyDeals').onchange=renderCatalog; $('#openCart').onclick=()=>$('#cart').classList.toggle('open'); $('#applyCoupon').onclick=()=>{const code=$('#couponInput').value.toUpperCase(); const r=Coupons.validate(code,Cart.items,Auth.session()); $('#couponMsg').textContent=r.ok?'Aplicado':'Inválido'; activeCoupon=r.ok?r.c:null; renderCatalog(); renderCart();}; }

document.addEventListener('DOMContentLoaded',()=>{try{$('#filterCat').innerHTML=`<option value='todas'>Todas</option>${CATEGORIES.map(c=>`<option value='${c}'>${c}</option>`).join('')}`; initAuth(); initAdmin(); bind(); renderCatalog(); renderCart(); reveal();}catch(e){console.error(e); document.body.innerHTML='<div class="panel">Error al cargar la tienda.</div>';}});
