import { useMemo, useState } from 'react'

type Property = { id:number; title:string; type:'Casa'|'Departamento'|'Terreno'; zone:'Centro'|'Norte'|'Sur'; rooms:number; price:number; location:string; description:string; image:string }
const data: Property[] = Array.from({length:20}).map((_,i)=>({id:i+1,title:`Propiedad ${i+1}`,type:(['Casa','Departamento','Terreno'] as const)[i%3],zone:(['Centro','Norte','Sur'] as const)[i%3],rooms:(i%5)+1,price:70000+i*9000,location:`${(['Centro','Norte','Sur'] as const)[i%3]}, Santa Fe`,description:'Excelente oportunidad con alto potencial.',image:['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'][i%3]}))

export default function App(){
  const [dark,setDark]=useState(true)
  const [zone,setZone]=useState('Todas'); const [type,setType]=useState('Todos'); const [max,setMax]=useState(300000)
  const [budget,setBudget]=useState(120000); const [loan,setLoan]=useState(100000); const [months,setMonths]=useState(24); const [rate,setRate]=useState(32)
  const [chatOpen,setChatOpen]=useState(false); const [toast,setToast]=useState('')
  const [msg,setMsg]=useState('')
  const filtered=useMemo(()=>data.filter(p=>(zone==='Todas'||p.zone===zone)&&(type==='Todos'||p.type===type)&&p.price<=max),[zone,type,max])
  const monthly=useMemo(()=>{const r=rate/100/12; return (loan*r)/(1-Math.pow(1+r,-months))},[loan,rate,months])
  const rec=useMemo(()=>data.filter(p=>p.price<=budget).slice(0,3),[budget])
  const c=dark?'bg-black text-white':'bg-zinc-100 text-zinc-900'
  return <div className={`${c} min-h-screen transition-colors duration-500`}>
    <section id='inicio' className='relative min-h-screen'><video className='absolute inset-0 w-full h-full object-cover' src='https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260403_050628_c4e32401-fab4-4a27-b7a8-6e9291cd5959.mp4' autoPlay loop muted playsInline/><div className='relative z-10 px-6 md:px-12 lg:px-16 pt-6 min-h-screen flex flex-col'><nav className='liquid-glass rounded-xl px-4 py-2 flex justify-between'><div>SF Inmobiliaria</div><div className='hidden md:flex gap-5'>{['inicio','propiedades','nosotros','contacto'].map(x=><a key={x} href={`#${x}`}>{x}</a>)}</div><button className='bg-white text-black px-4 rounded-lg' onClick={()=>setDark(v=>!v)}>{dark?'Claro':'Oscuro'}</button></nav><div className='mt-auto pb-16'><h1 className='text-5xl'>Encontrá tu próximo hogar<br/>en Santa Fe.</h1></div></div></section>
    <section id='propiedades' className='px-6 md:px-12 lg:px-16 py-12'><h2 className='text-3xl mb-4'>Propiedades disponibles</h2><div className='grid md:grid-cols-4 gap-3 mb-6 liquid-glass p-3 rounded-xl'><select value={zone} onChange={e=>setZone(e.target.value)} className='bg-black/40 border border-white/20 rounded p-2'><option>Todas</option><option>Centro</option><option>Norte</option><option>Sur</option></select><select value={type} onChange={e=>setType(e.target.value)} className='bg-black/40 border border-white/20 rounded p-2'><option>Todos</option><option>Casa</option><option>Departamento</option><option>Terreno</option></select><div>USD {max.toLocaleString()} <input type='range' min={50000} max={300000} step={5000} value={max} onChange={e=>setMax(Number(e.target.value))}/></div><button onClick={()=>{setToast('Consulta reciente en esta zona'); setTimeout(()=>setToast(''),2500)}} className='border border-white/20 rounded p-2'>Simular notificación</button></div><div className='grid md:grid-cols-4 gap-4'>{filtered.map(p=><article key={p.id} className='liquid-glass rounded-xl overflow-hidden border border-white/20 hover:-translate-y-1 transition-all'><img src={p.image} className='h-40 w-full object-cover'/><div className='p-3'><p>{p.type} · {p.zone}</p><p>USD {p.price.toLocaleString()}</p><button className='mt-2 bg-white text-black px-3 py-1 rounded' onClick={()=>window.open(`https://wa.me/549XXXXXXXXXX?text=Hola%20quiero%20consultar%20por%20${encodeURIComponent(p.title)}`,'_blank')}>WhatsApp</button></div></article>)}</div></section>
    <section className='px-6 md:px-12 lg:px-16 py-10 grid md:grid-cols-2 gap-5'><div className='liquid-glass p-5 rounded-xl'><h3>Simulador de compra</h3><p>Presupuesto USD {budget.toLocaleString()}</p><input type='range' min={50000} max={300000} step={5000} value={budget} onChange={e=>setBudget(Number(e.target.value))}/>{rec.map(r=><p key={r.id} className='text-sm'>{r.title} - USD {r.price.toLocaleString()}</p>)}</div><div className='liquid-glass p-5 rounded-xl'><h3>Simulador de crédito</h3><p>Monto USD {loan.toLocaleString()}</p><input type='range' min={50000} max={250000} step={5000} value={loan} onChange={e=>setLoan(Number(e.target.value))}/><p>Interés anual {rate}%</p><input type='range' min={10} max={60} value={rate} onChange={e=>setRate(Number(e.target.value))}/><select value={months} onChange={e=>setMonths(Number(e.target.value))} className='bg-black/40 border border-white/20 rounded p-2'><option value={12}>12</option><option value={24}>24</option><option value={60}>60</option></select><p>Cuota mensual estimada: USD {isFinite(monthly)?monthly.toFixed(0):'0'}</p></div></section>
    <section id='nosotros' className='px-6 md:px-12 lg:px-16 py-10'><div className='liquid-glass p-6 rounded-xl'><h2 className='text-3xl mb-3'>Nosotros</h2><p>Somos una inmobiliaria con amplia experiencia en Santa Fe, enfocada en operaciones seguras, asesoramiento profesional y resultados medibles para compradores e inversores.</p><p className='mt-2 text-gray-300'>Misión: simplificar la compra y venta con transparencia, tecnología y acompañamiento humano.</p></div></section>
    <footer id='contacto' className='px-6 md:px-12 lg:px-16 py-10'><div className='liquid-glass rounded-xl p-6 grid md:grid-cols-2 gap-6'><div><h3 className='text-2xl mb-3'>Contacto</h3><p>Dirección: Bv. Gálvez 1450, Santa Fe</p><p>Horario: Lun-Vie 9:00 a 18:00</p><p>Tel: +54 342 456 7890</p><p>Email: contacto@sfinmobiliaria.com.ar</p></div><iframe title='mapa' src='https://www.google.com/maps?q=Santa+Fe,+Argentina&output=embed' className='w-full h-56 rounded-xl'/></div></footer>
    {toast && <div className='fixed top-6 right-6 bg-white text-black px-4 py-2 rounded-lg shadow-xl z-50'>{toast}</div>}
    <button onClick={()=>setChatOpen(true)} className='fixed bottom-6 right-6 bg-white text-black px-5 py-3 rounded-full z-50 animate-pulse'>¿Querés que te recomiende propiedades?</button>
    {chatOpen && <div className='fixed inset-0 bg-black/70 z-50 flex items-center justify-center p-4'><div className='liquid-glass rounded-xl p-6 w-full max-w-md'><h3 className='text-xl mb-2'>Asesor virtual</h3><p className='text-sm mb-3'>Hola 👋, contame qué tipo de propiedad buscás y te recomiendo opciones.</p><input value={msg} onChange={e=>setMsg(e.target.value)} placeholder='Ej: casa con patio en zona norte' className='w-full bg-black/40 border border-white/20 rounded p-2 mb-3'/><div className='flex gap-2'><button onClick={()=>window.open(`https://wa.me/549XXXXXXXXXX?text=${encodeURIComponent(msg||'Hola quiero asesoramiento')}`,'_blank')} className='bg-white text-black px-4 py-2 rounded'>Enviar a WhatsApp</button><button onClick={()=>setChatOpen(false)} className='border border-white/20 px-4 py-2 rounded'>Cerrar</button></div></div></div>}
  </div>
}
